apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-chart.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helm-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- if gt (len .Values.volumes) 0 }}
      volumes:
        {{- tpl (toYaml .Values.volumes) . | nindent 8 }}
      {{- end }}
      {{- if gt (len .Values.initContainers) 0 }}
      initContainers:
        {{- tpl (toYaml .Values.initContainers) . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "helm-chart.name" . }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if gt (len .Values.command) 0 }}
          command:
            {{- tpl (toYaml .Values.command) . | nindent 12 }}
          {{- end }}
          {{- if gt (len .Values.args) 0 }}
          args:
            {{- tpl (toYaml .Values.args) . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          {{- if gt (len .Values.env) 0 }}
          env:
            {{- tpl (toYaml .Values.env) . | nindent 12 }}
          {{- end }}
          {{- if gt (len .Values.envFrom) 0 }}
          envFrom:
            {{- tpl (toYaml .Values.envFrom) . | nindent 12 }}
          {{- end }}
          {{- if .Values.resources.enabled }}
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            httpGet:
              path: {{ .Values.livenessProbe.httpGet.path }}
              port: {{ tpl (.Values.livenessProbe.httpGet.port) . }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds}}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold}}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds}}
            httpGet:
              path: {{ .Values.readinessProbe.httpGet.path }}
              port: {{ tpl (.Values.readinessProbe.httpGet.port) . }}
          {{- end }}
          {{- if gt (len .Values.volumeMounts) 0 }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
          {{- end }}
