name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:

      - name: Checkout main
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Extract tag version
        id: versioning
        run: |
          tag=${GITHUB_REF/refs\/tags\//}
          echo $tag
          echo "tag_version=$tag" >> "$GITHUB_ENV"

      - name: Extract chart version
        id: chart_version
        run: |
          CHART_VERSION=$(cat helm/Chart.yaml | grep ^version:)
          CHART_VERSION=${CHART_VERSION#version: }
          echo $CHART_VERSION
          echo "chart_version=$CHART_VERSION" >> "$GITHUB_ENV"

      - name: Ensure tag and chart version matches
        run: |
          TAG_VERSION="${{ env.tag_version }}"
          echo "TAG_VERSION=${TAG_VERSION}"
          
          CHART_VERSION="${{ env.chart_version }}"
          echo "${CHART_VERSION=CHART_VERSION}"
          
          if [ -z "${TAG_VERSION}" ]
          then
              echo "Tag version is empty"
              exit 1
          fi
          if [ -z "${CHART_VERSION}" ]
          then
              echo "Chart version is empty"
              exit 1
          fi
          if [ "$TAG_VERSION" != "$CHART_VERSION" ]
          then
              echo "Tag version does not match chart version"
              exit 1
          fi

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Publishing to the Helm repository
        run: |
          TAG_VERSION="${{ env.tag_version }}"
          
          git config --global user.email "action@github.com"
          git config --global user.name "Github Action"
          git checkout main
          
          ./.github/ci/package.sh
          
          git add .
          git commit -m "Publishing $TAG_VERSION to the Helm repository"
          git push origin main