name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:

      - name: Checkout main
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Extract tag version
        id: versioning
        run: |
          tag=${GITHUB_REF/refs\/tags\//}
          echo $tag
          echo "{tag_version}={tag}" >> $GITHUB_OUTPUT

      - name: Extract chart version
        id: chart_version
        run: |
          CHART_VERSION=$(cat helm/Chart.yaml | grep ^version:)
          CHART_VERSION=${CHART_VERSION#version: }
          echo $CHART_VERSION
          echo "{chart_version}={CHART_VERSION}" >> $GITHUB_OUTPUT

      - name: Ensure tag and chart version matches
        run: |
          echo "$TAG_VERSION"
          echo "$CHART_VERSION"
          if [ "$TAG_VERSION" != "$CHART_VERSION" ]
          then
              echo "Tag version does not match chart version"
              exit 1
          fi
        env:
          TAG_VERSION: ${{ steps.versioning.outputs.tag_version }}
          CHART_VERSION: ${{ steps.chart_version.outputs.chart_version }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Publishing to the Helm repository
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "Github Action"
          git checkout main
          
          ./.github/ci/package.sh
          
          git add .
          git commit -m "Publishing $TAG_VERSION to the Helm repository"
          git push origin main
        env:
          TAG_VERSION: ${{ steps.versioning.outputs.tag_version }}